# Generated by Django 4.2.7 on 2026-01-10 13:15

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavedAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("address2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Saved Addresses",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="SavedPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weight_lbs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weight_oz",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Saved Packages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ship_from_first_name", models.CharField(blank=True, max_length=100)),
                ("ship_from_last_name", models.CharField(blank=True, max_length=100)),
                ("ship_from_address", models.CharField(blank=True, max_length=200)),
                ("ship_from_address2", models.CharField(blank=True, max_length=200)),
                ("ship_from_city", models.CharField(blank=True, max_length=100)),
                ("ship_from_state", models.CharField(blank=True, max_length=2)),
                ("ship_from_zip", models.CharField(blank=True, max_length=10)),
                ("ship_from_phone", models.CharField(blank=True, max_length=20)),
                ("ship_to_first_name", models.CharField(max_length=100)),
                ("ship_to_last_name", models.CharField(blank=True, max_length=100)),
                ("ship_to_address", models.CharField(max_length=200)),
                ("ship_to_address2", models.CharField(blank=True, max_length=200)),
                ("ship_to_city", models.CharField(max_length=100)),
                ("ship_to_state", models.CharField(max_length=2)),
                ("ship_to_zip", models.CharField(max_length=10)),
                ("ship_to_phone", models.CharField(blank=True, max_length=20)),
                (
                    "weight_lbs",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weight_oz",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("item_sku", models.CharField(blank=True, max_length=100)),
                ("order_no", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("default_applied", "Default Applied"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                (
                    "address_validation_status",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "address_validation_source",
                    models.CharField(blank=True, max_length=50),
                ),
                ("address_validation_message", models.TextField(blank=True)),
                (
                    "shipping_service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("priority_mail", "Priority Mail"),
                            ("ground_shipping", "Ground Shipping"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "calculated_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="apps_shipme_status_265423_idx"),
                    models.Index(fields=["order_no"], name="apps_shipme_order_n_9a2cb1_idx"),
                ],
            },
        ),
    ]
